dist: trusty
sudo: true

os:
  - linux

compiler:
  - gcc
  - clang

language: c

env:
  global:
    - secure: "IrlWvVLYTS+zVEDTITlcwBIBo5VGWuoAsSDIVHsrdbDxEPr+ysDlYxq27WEWuOf+Um3/S6pch6jkEfhYFb24Bd+F7JkmW+Sv7gBXXYGwDpM6oJENiFt1OajTcOSFMqJ9UirvGoSzzx7SwCH6zUC5YUd/LJgmJLKIMI8f7vYjRAg="

addons:
  coverity_scan:
    project:
      name: "yabok/yasl"
      description: "Build submitted via Travis CI"
    notification_email: yasl@kyriasis.com
    build_command_prepend: cov-configure --template --comptype clangcc --compiler clang && ./configure.bash
    build_command: make
    branch_pattern: coverity_scan

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-sphinx python3-pip

install:
  - export PATH="`pwd`/build:${PATH}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build; fi
  - sudo pip3 install meson

script:
  - CC="$CC" meson builddir
  - ninja -C builddir
  - ninja -C builddir test
